# Generated by Django 5.2.4 on 2025-07-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yozuvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('W', 'Writer'), ('P', 'Poet'), ('U', 'User')], max_length=1)),
            ],
        ),
    ]
